wip
Signed-off-by: Filippo Costa <filippo@sovlabs.io>

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -57,13 +57,14 @@ env:
 # Source: <https://stackoverflow.com/a/72408109/5148606>
 concurrency:
   group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
-  cancel-in-progress: true
+  # Except in `nightly` and `stable` branches! Any cancelled job will cause the
+  # CI run to fail, and we want to keep a clean history for major branches.
+  cancel-in-progress: ${{ (github.ref == 'refs/heads/nightly') || (github.ref == 'refs/heads/stable') }}
 
 jobs:
   check:
     name: check
-    runs-on:
-      group: 4-cores_16GB_Ubuntu Group
+    runs-on: ubuntu-latest
     timeout-minutes: 60
     steps:
       - uses: actions/checkout@v3
@@ -74,6 +75,7 @@ jobs:
         with:
           shared-key: cargo-check
           save-if: ${{ github.ref == 'refs/heads/nightly' }}
+          cache-all-crates: true # For cargo-hack.
           workspaces: |
             .
             examples/demo-prover
@@ -90,8 +92,7 @@ jobs:
     # building dependencies, only chceking them, so we can share caches
     # effectively.
     needs: check
-    runs-on:
-      group: 4-cores_16GB_Ubuntu Group
+    runs-on: ubuntu-latest
     timeout-minutes: 60
     steps:
       - uses: actions/checkout@v3
@@ -104,6 +105,7 @@ jobs:
         with:
           shared-key: cargo-check
           save-if: ${{ github.ref == 'refs/heads/nightly' }}
+          cache-all-crates: true # For cargo-hack.
           workspaces: |
             .
             examples/demo-prover
@@ -111,8 +113,7 @@ jobs:
       - name: cargo hack
         run: make check-features
   test:
-    runs-on:
-      group: 4-cores_16GB_Ubuntu Group
+    runs-on: ubuntu-latest
     timeout-minutes: 60
     steps:
       - uses: actions/checkout@v3
@@ -137,8 +138,7 @@ jobs:
     # `test` has already built dependencies, so we can share
     # caches (the profile is `dev` in both cases).
     needs: test
-    runs-on:
-      group: 8-cores_32GB_Ubuntu Group
+    runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - uses: rui314/setup-mold@v1
@@ -201,8 +201,7 @@ jobs:
   # profile from the rest of the codebase, so caches can't be shared.
   check-demo-prover:
     name: check demo prover
-    runs-on:
-      group: 4-cores_16GB_Ubuntu Group
+    runs-on: ubuntu-latest
     timeout-minutes: 90
     steps:
       - uses: actions/checkout@v3
@@ -226,8 +225,7 @@ jobs:
             exit 1
           fi
   coverage:
-    runs-on:
-      group: 8-cores_32GB_Ubuntu Group
+    runs-on: ubuntu-latest
     timeout-minutes: 90
     steps:
       - uses: actions/checkout@v3
